{
 "title": "01 - Probe Summary",
 "description": "High Level Summary of Performance Data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "DNS_TARGET1",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=1)"
   },
   {
    "name": "DNS_TARGET2",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=2)"
   },
   {
    "name": "DNS_TARGET3",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=3)"
   },
   {
    "name": "DNS_TARGET4",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=4)"
   },
   {
    "name": "DNS_TARGET5",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=5)"
   },
   {
    "name": "HTTP_TARGET1",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)"
   },
   {
    "name": "HTTP_TARGET2",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=2)"
   },
   {
    "name": "HTTP_TARGET3",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=3)"
   },
   {
    "name": "HTTP_TARGET4",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=4)"
   },
   {
    "name": "HTTP_TARGET5",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=5)"
   },
   {
    "name": "PING_TARGET1",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 1) "
   },
   {
    "name": "PING_TARGET2",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 2)"
   },
   {
    "name": "PING_TARGET3",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 3) "
   },
   {
    "name": "PING_TARGET4",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 4) "
   },
   {
    "name": "PING_TARGET5",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 5) "
   },
   {
    "name": "WLANPi",
    "label": "Select Probe:",
    "query": "select  \"host\", \"network\" from \"wiperf-poll-status\" where time >= now() - 14d"
   }
  ]
 },
 "panels": [
  {
   "title": "Speedtest (Download/Upload) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wiperf-speedtest",
     "select": [
      [
       { "params": [ "download_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Download Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wiperf-speedtest",
     "select": [
      [
       { "params": [ "upload_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Upload Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Connection Rates/Signal - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Phy Rate (Mbps)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "tx_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx PHY Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "rx_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx PHY Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "signal_level_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Signal Level (dBm)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "DNS Lookup Time (mS) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "mS" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dns",
     "query": "SELECT last(\"lookup_time_ms\") AS \"$DNS_TARGET1\" FROM \"wiperf-dns\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"dns_target\" =~ /^$DNS_TARGET1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$DNS_TARGET1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "dns_target", "operator": "=~", "value": "/^$DNS_TARGET1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dns",
     "query": "SELECT last(\"lookup_time_ms\") AS \"$DNS_TARGET1\" FROM \"wiperf-dns\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"dns_target\" =~ /^$DNS_TARGET1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$DNS_TARGET2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "dns_target", "operator": "=~", "value": "/^$DNS_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dns",
     "query": "SELECT last(\"lookup_time_ms\") AS \"$DNS_TARGET1\" FROM \"wiperf-dns\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"dns_target\" =~ /^$DNS_TARGET1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$DNS_TARGET3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "dns_target", "operator": "=~", "value": "/^$DNS_TARGET3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dns",
     "query": "SELECT last(\"lookup_time_ms\") AS \"$DNS_TARGET1\" FROM \"wiperf-dns\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"dns_target\" =~ /^$DNS_TARGET1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$DNS_TARGET4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "dns_target", "operator": "=~", "value": "/^$DNS_TARGET4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dns",
     "query": "SELECT last(\"lookup_time_ms\") AS \"$DNS_TARGET1\" FROM \"wiperf-dns\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"dns_target\" =~ /^$DNS_TARGET1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$DNS_TARGET5" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "dns_target", "operator": "=~", "value": "/^$DNS_TARGET5$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Get Time (mS) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET2}" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET5" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET5$/" }
     ]
    }
   ]
  },
  {
   "title": "DHCP Renewal Time - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "DHDP Renewal (mS)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dhcp",
     "select": [
      [
       { "params": [ "renewal_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DHCP Renewal (mS)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP iperf3 rate - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-iperf3-tcp",
     "select": [
      [
       { "params": [ "sent_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Sent Mbps" ], "type": "alias" }
      ],
      [
       { "params": [ "received_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rec Mbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Ping Targets RTT Avg Times  - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms", "label": "Ping RTT (mS)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "wiperf-ping",
     "query": "SELECT \"rtt_avg_ms\" AS \"${PING_TARGET1}\" FROM \"wiperf-ping\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\"=1) AND $timeFilter",
     "select": [
      [
       { "params": [ "rtt_avg_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "ping_index", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "wiperf-ping",
     "query": "SELECT \"rtt_avg_ms\" AS \"${PING_TARGET2}\" FROM \"wiperf-ping\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\"=2) AND $timeFilter",
     "select": [
      [
       { "params": [ "rtt_avg_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "ping_index", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "wiperf-ping",
     "query": "SELECT \"rtt_avg_ms\" AS \"${PING_TARGET3}\" FROM \"wiperf-ping\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\"=3) AND $timeFilter",
     "select": [
      [
       { "params": [ "rtt_avg_ms" ], "type": "field" },
       { "params": [ "${PING_TARGET2}" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "ping_host", "operator": "=~", "value": "/^$PING_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "wiperf-ping",
     "query": "SELECT \"rtt_avg_ms\" AS \"${PING_TARGET4}\" FROM \"wiperf-ping\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\"=4) AND $timeFilter",
     "select": [
      [
       { "params": [ "rtt_avg_ms" ], "type": "field" },
       { "params": [ "${PING_TARGET2}" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "ping_host", "operator": "=~", "value": "/^$PING_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "wiperf-ping",
     "query": "SELECT \"rtt_avg_ms\" AS \"${PING_TARGET5}\" FROM \"wiperf-ping\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\"=5) AND $timeFilter",
     "select": [
      [
       { "params": [ "rtt_avg_ms" ], "type": "field" },
       { "params": [ "${PING_TARGET2}" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "ping_host", "operator": "=~", "value": "/^$PING_TARGET2$/" }
     ]
    }
   ]
  },
  {
   "title": "UDP iperf3 Throughput - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-iperf3-udp",
     "select": [
      [
       { "params": [ "mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "UDP Throughput" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "UDP iperf3 Throughput/Jitter - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms", "label": "Jitter (mS)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-iperf3-udp",
     "select": [
      [
       { "params": [ "jitter_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Jitter(ms)" ], "type": "alias" }
      ],
      [
       { "params": [ "lost_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "% Loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  { "title": "Poller Status Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Poll Status - $WLANPi",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "wiperf-poll-status",
     "select": [
      [
       { "params": [ "network" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Network Test" ], "type": "alias" }
      ],
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IP Address" ], "type": "alias" }
      ],
      [
       { "params": [ "speedtest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Speedtest" ], "type": "alias" }
      ],
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ping Test" ], "type": "alias" }
      ],
      [
       { "params": [ "dns" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DNS Test" ], "type": "alias" }
      ],
      [
       { "params": [ "http" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "HTTP Test" ], "type": "alias" }
      ],
      [
       { "params": [ "iperf_tcp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TCP iperf" ], "type": "alias" }
      ],
      [
       { "params": [ "iperf_udp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "UDP iperf" ], "type": "alias" }
      ],
      [
       { "params": [ "dhcp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DHCP Test" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  }
 ]
}