{
 "title": "01 - Probe Summary",
 "description": "High Level Summary of Performance Data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "DNS_TARGET1",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=1)"
   },
   {
    "name": "DNS_TARGET2",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=2)"
   },
   {
    "name": "DNS_TARGET3",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=3)"
   },
   {
    "name": "DNS_TARGET4",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=4)"
   },
   {
    "name": "DNS_TARGET5",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=5)"
   },
   {
    "name": "HTTP_TARGET1",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)"
   },
   {
    "name": "HTTP_TARGET2",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=2)"
   },
   {
    "name": "HTTP_TARGET3",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=3)"
   },
   {
    "name": "HTTP_TARGET4",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=4)"
   },
   {
    "name": "HTTP_TARGET5",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=5)"
   },
   {
    "name": "PING_TARGET1",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 1) "
   },
   {
    "name": "PING_TARGET2",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 2)"
   },
   {
    "name": "PING_TARGET3",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 3) "
   },
   {
    "name": "PING_TARGET4",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 4) "
   },
   {
    "name": "PING_TARGET5",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 5) "
   },
   {
    "name": "WLANPi",
    "label": "Select Probe:",
    "query": "select  \"host\", \"network\" from \"wiperf-poll-status\" where time >= now() - 14d"
   },
   {
    "name": "SMB_TARGET1",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=1)"
   },
   {
    "name": "SMB_TARGET2",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=2)"
   },
   {
    "name": "SMB_TARGET3",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=3)"
   },
   {
    "name": "SMB_TARGET4",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=4)"
   },
   {
    "name": "SMB_TARGET5",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=5)"
   },
   {
    "name": "SMB_FILENAME1",
    "query": "SELECT last(\"filename\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=1)"
   },
   {
    "name": "SMB_FILENAME2",
    "query": "SELECT last(\"filename\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=2)"
   },
   {
    "name": "SMB_FILENAME3",
    "query": "SELECT last(\"filename\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=3)"
   },
   {
    "name": "SMB_FILENAME4",
    "query": "SELECT last(\"filename\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=4)"
   },
   {
    "name": "SMB_FILENAME5",
    "query": "SELECT last(\"filename\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=5)"
   }
  ]
 },
 "panels": [
  { "title": "Performance Summary Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Speedtest (Download/Upload) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wiperf-speedtest",
     "select": [
      [
       { "params": [ "download_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Download Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wiperf-speedtest",
     "select": [
      [
       { "params": [ "upload_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Upload Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Connection Rates/Signal - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Phy Rate (Mbps)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "tx_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx PHY Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "rx_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx PHY Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "signal_level_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Signal Level (dBm)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "DNS Lookup Time (mS) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "mS" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dns",
     "query": "SELECT last(\"lookup_time_ms\") AS \"$DNS_TARGET1\" FROM \"wiperf-dns\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"dns_target\" =~ /^$DNS_TARGET1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$DNS_TARGET1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "dns_target", "operator": "=~", "value": "/^$DNS_TARGET1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dns",
     "query": "SELECT last(\"lookup_time_ms\") AS \"$DNS_TARGET1\" FROM \"wiperf-dns\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"dns_target\" =~ /^$DNS_TARGET1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$DNS_TARGET2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "dns_target", "operator": "=~", "value": "/^$DNS_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dns",
     "query": "SELECT last(\"lookup_time_ms\") AS \"$DNS_TARGET1\" FROM \"wiperf-dns\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"dns_target\" =~ /^$DNS_TARGET1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$DNS_TARGET3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "dns_target", "operator": "=~", "value": "/^$DNS_TARGET3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dns",
     "query": "SELECT last(\"lookup_time_ms\") AS \"$DNS_TARGET1\" FROM \"wiperf-dns\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"dns_target\" =~ /^$DNS_TARGET1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$DNS_TARGET4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "dns_target", "operator": "=~", "value": "/^$DNS_TARGET4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dns",
     "query": "SELECT last(\"lookup_time_ms\") AS \"$DNS_TARGET1\" FROM \"wiperf-dns\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"dns_target\" =~ /^$DNS_TARGET1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "lookup_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$DNS_TARGET5" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "dns_target", "operator": "=~", "value": "/^$DNS_TARGET5$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server Response (mS) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET1} - " ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET2} -  " ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET3} -  " ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET4} - " ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET5} -  " ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET5$/" }
     ]
    }
   ]
  },
  {
   "title": "Ping Targets RTT Avg Times  - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "Ping RTT (mS)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-ping",
     "query": "SELECT \"rtt_avg_ms\" AS \"${PING_TARGET1}\" FROM \"wiperf-ping\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\"=1) AND $timeFilter",
     "select": [
      [
       { "params": [ "rtt_avg_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$PING_TARGET1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "ping_host", "operator": "=~", "value": "/^$PING_TARGET1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-ping",
     "query": "SELECT \"rtt_avg_ms\" AS \"${PING_TARGET1}\" FROM \"wiperf-ping\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\"=1) AND $timeFilter",
     "select": [
      [
       { "params": [ "rtt_avg_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$PING_TARGET2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "ping_host", "operator": "=~", "value": "/^$PING_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-ping",
     "query": "SELECT \"rtt_avg_ms\" AS \"${PING_TARGET1}\" FROM \"wiperf-ping\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\"=1) AND $timeFilter",
     "select": [
      [
       { "params": [ "rtt_avg_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$PING_TARGET3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "ping_host", "operator": "=~", "value": "/^$PING_TARGET3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-ping",
     "query": "SELECT \"rtt_avg_ms\" AS \"${PING_TARGET1}\" FROM \"wiperf-ping\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\"=1) AND $timeFilter",
     "select": [
      [
       { "params": [ "rtt_avg_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$PING_TARGET4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "ping_host", "operator": "=~", "value": "/^$PING_TARGET4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-ping",
     "query": "SELECT \"rtt_avg_ms\" AS \"${PING_TARGET1}\" FROM \"wiperf-ping\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\"=1) AND $timeFilter",
     "select": [
      [
       { "params": [ "rtt_avg_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$PING_TARGET5" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "ping_host", "operator": "=~", "value": "/^$PING_TARGET5$/" }
     ]
    }
   ]
  },
  {
   "title": "DHCP Renewal Time - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "DHDP Renewal (mS)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-dhcp",
     "query": "SELECT last(\"renewal_time_ms\") AS \"DHCP Renewal (mS)\" FROM \"wiperf-dhcp\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "renewal_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DHCP Renewal (mS)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "iPerf",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP iperf3 rate - $WLANPi",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "Mbits" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-iperf3-tcp",
       "select": [
        [
         { "params": [ "sent_mbps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Sent Mbps" ], "type": "alias" }
        ],
        [
         { "params": [ "received_mbps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Rec Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
       ]
      }
     ]
    },
    {
     "title": "UDP iperf3 Throughput - $WLANPi",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "Mbits" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-iperf3-udp",
       "select": [
        [
         { "params": [ "mbps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "UDP Throughput" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
       ]
      }
     ]
    },
    {
     "title": "UDP iperf3 Jitter/Loss - $WLANPi",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "ms", "label": "Jitter (mS)" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-iperf3-udp",
       "select": [
        [
         { "params": [ "jitter_ms" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Jitter(ms)" ], "type": "alias" }
        ],
        [
         { "params": [ "lost_percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "% Loss" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SMB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "SMB Transfer Rate - $WLANPi",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "Mbits", "label": "Time to transfert" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-smb",
       "select": [
        [
         { "params": [ "smb_rate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [
           "${SMB_TARGET1} ${SMB_FILENAME1} "
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
        { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET1$/" },
        { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME1$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-smb",
       "select": [
        [
         { "params": [ "smb_rate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [
           "${SMB_TARGET2} ${SMB_FILENAME2} "
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
        { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET2$/" },
        { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME2$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-smb",
       "select": [
        [
         { "params": [ "smb_rate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [
           "${SMB_TARGET3} ${SMB_FILENAME3} "
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
        { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET3$/" },
        { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME3$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-smb",
       "select": [
        [
         { "params": [ "smb_rate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [
           "${SMB_TARGET4} ${SMB_FILENAME4} "
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
        { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET4$/" },
        { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME4$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-smb",
       "select": [
        [
         { "params": [ "smb_rate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [
           "${SMB_TARGET5} ${SMB_FILENAME5} "
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
        { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET5$/" },
        { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME5$/" }
       ]
      }
     ]
    },
    {
     "title": "SMB Transfer Time - $WLANPi",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "s", "label": "Transfer Time (s)" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-smb",
       "select": [
        [
         { "params": [ "smb_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "${SMB_TARGET1} $SMB_FILENAME1" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
        { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET1$/" },
        { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME1$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-smb",
       "select": [
        [
         { "params": [ "smb_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "${SMB_TARGET2} $SMB_FILENAME2 " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
        { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET2$/" },
        { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME2$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-smb",
       "select": [
        [
         { "params": [ "smb_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "${SMB_TARGET3} $SMB_FILENAME3" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
        { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET3$/" },
        { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME3$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-smb",
       "select": [
        [
         { "params": [ "smb_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "${SMB_TARGET4} $SMB_FILENAME4" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
        { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET4$/" },
        { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME4$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wiperf-smb",
       "select": [
        [
         { "params": [ "smb_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "${SMB_TARGET5} $SMB_FILENAME5" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
        { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET5$/" },
        { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME5$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Poller Status Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Poll Status - $WLANPi",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "5m" ], "type": "time" }
       ],
       "measurement": "wiperf-poll-status",
       "query": "SELECT last(\"network\") AS \"Network\", last(\"ip\") AS \"IP Address\", last(\"speedtest\") AS \"Speedtest\", last(\"ping\") AS \"Ping Test\", last(\"dns\") AS \"DNS Test\", last(\"http\") AS \"HTTP Test\", last(\"iperf_tcp\") AS \"TCP iperf\", last(\"iperf_udp\") AS \"UDP iperf\", last(\"dhcp\") AS \"DHCP Test\", last(\"smb\") AS \"SMB Test\", last(\"auth\") AS \"Auth Test\", last(\"probe_mode\") AS \"Mode\", last(\"mgt_if\") AS \"Mgt I/F\", last(\"run_time\") AS \"Poll Cycle (s)\" FROM \"wiperf-poll-status\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter GROUP BY time(5m)",
       "select": [
        [
         { "params": [ "network" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Network" ], "type": "alias" }
        ],
        [
         { "params": [ "ip" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "IP Address" ], "type": "alias" }
        ],
        [
         { "params": [ "speedtest" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Speedtest" ], "type": "alias" }
        ],
        [
         { "params": [ "ping" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Ping Test" ], "type": "alias" }
        ],
        [
         { "params": [ "dns" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "DNS Test" ], "type": "alias" }
        ],
        [
         { "params": [ "http" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "HTTP Test" ], "type": "alias" }
        ],
        [
         { "params": [ "iperf_tcp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "TCP iperf" ], "type": "alias" }
        ],
        [
         { "params": [ "iperf_udp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "UDP iperf" ], "type": "alias" }
        ],
        [
         { "params": [ "dhcp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "DHCP Test" ], "type": "alias" }
        ],
        [
         { "params": [ "smb" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "SMB Test" ], "type": "alias" }
        ],
        [
         { "params": [ "auth" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Auth Test" ], "type": "alias" }
        ],
        [
         { "params": [ "probe_mode" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Mode" ], "type": "alias" }
        ],
        [
         { "params": [ "mgt_if" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Mgt I/F" ], "type": "alias" }
        ],
        [
         { "params": [ "run_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Poll Cycle (s)" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}