{
 "title": "02 - Speedtest Report",
 "description": "High Level Summary of Performance Data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WLANPi",
    "label": "Select Probe:",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Speedtest (Download/Upload) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wiperf-speedtest",
     "select": [
      [
       { "params": [ "download_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Download Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wiperf-speedtest",
     "select": [
      [
       { "params": [ "upload_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Upload Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Connection Rates/Signal - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Phy Rate (Mbps)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "tx_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx PHY Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "rx_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx PHY Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "signal_level_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Signal Level (dBm)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Layer 2 TX Retries - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "L2 Retry Count" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "wiperf-network",
     "query": "SELECT difference(last(\"tx_retries\")) AS \"TX Retry Count\" FROM \"wiperf-network\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "tx_retries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TX Retry Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless MCS (if supported by NIC) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "MCS" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "tx_mcs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx MCS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "rx_mcs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx MCS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Connection Details - $WLANPi",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "wiperf-network",
     "query": "SELECT \"bssid\" AS \"BSSID\", \"ssid\" AS \"SSID\", \"channel\" AS \"Channel\", \"channel_width\" AS \"Channel Width\", \"tx_rate_mbps\" AS \"Tx Phy Rate (Mbps)\", \"rx_rate_mbps\" AS \"Rx Phy Rate (Mbps)\", \"signal_level_dbm\" AS \"RSSI (dBm)\" FROM \"wiperf-network\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bssid" ], "type": "field" },
       { "params": [ "BSSID" ], "type": "alias" }
      ],
      [
       { "params": [ "ssid" ], "type": "field" },
       { "params": [ "SSID" ], "type": "alias" }
      ],
      [
       { "params": [ "channel" ], "type": "field" },
       { "params": [ "Channel" ], "type": "alias" }
      ],
      [
       { "params": [ "channel_width" ], "type": "field" },
       { "params": [ "Width (MHz)" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_rate_mbps" ], "type": "field" },
       { "params": [ "Tx Rate (Mbps)" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_rate_mbps" ], "type": "field" },
       { "params": [ "Rx Rate (Mbps)" ], "type": "alias" }
      ],
      [
       { "params": [ "signal_level_dbm" ], "type": "field" },
       { "params": [ "RSSI (dBm)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Speedtest Details  - $WLANPi",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "wiperf-speedtest",
     "query": "SELECT \"ssid\" AS \"SSID\" FROM \"wiperf-network\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "server_name" ], "type": "field" },
       { "params": [ "Speedtest Server" ], "type": "alias" }
      ],
      [
       { "params": [ "download_rate_mbps" ], "type": "field" },
       { "params": [ "Download Rate (Mbps)" ], "type": "alias" }
      ],
      [
       { "params": [ "upload_rate_mbps" ], "type": "field" },
       { "params": [ "Upload Rate (Mbps)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  }
 ]
}