{
 "title": "05 - HTTP Report",
 "description": "High Level Summary of Performance Data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DNS_TARGET1",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=1)"
   },
   {
    "name": "DNS_TARGET2",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=2)"
   },
   {
    "name": "DNS_TARGET3",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=3)"
   },
   {
    "name": "DNS_TARGET4",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=4)"
   },
   {
    "name": "DNS_TARGET5",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=5)"
   },
   {
    "name": "HTTP_TARGET1",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)"
   },
   {
    "name": "HTTP_TARGET2",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=2)"
   },
   {
    "name": "HTTP_TARGET3",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=3)"
   },
   {
    "name": "HTTP_TARGET4",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=4)"
   },
   {
    "name": "HTTP_TARGET5",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=5)"
   },
   {
    "name": "PING_TARGET1",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 1) "
   },
   {
    "name": "PING_TARGET2",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 2) "
   },
   {
    "name": "PING_TARGET3",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 3) "
   },
   {
    "name": "PING_TARGET4",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 4) "
   },
   {
    "name": "PING_TARGET5",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 5) "
   },
   {
    "name": "WLANPi",
    "label": "Select Probe:",
    "query": "select  \"host\", \"network\" from \"wiperf-poll-status\" where time >= now() - 14d"
   }
  ]
 },
 "panels": [
  { "title": "HTTP Performance Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Server Response (mS) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET5" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET5$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Page Load (mS) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_get_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_get_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_get_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_get_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_get_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET5" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET5$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Status - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Stacked Status" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"http_status_code\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"http_index\" = 1)",
     "select": [
      [
       { "params": [ "http_status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"http_status_code\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"http_index\" = 1)",
     "select": [
      [
       { "params": [ "http_status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"http_status_code\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"http_index\" = 1)",
     "select": [
      [
       { "params": [ "http_status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"http_status_code\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"http_index\" = 1)",
     "select": [
      [
       { "params": [ "http_status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"http_status_code\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"http_index\" = 1)",
     "select": [
      [
       { "params": [ "http_status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$HTTP_TARGET5" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET5$/" }
     ]
    }
   ]
  },
  {
   "title": "$HTTP_TARGET1 - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "HTTP Get Time" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_get_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET1} Page Load" ], "type": "alias" }
      ],
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${HTTP_TARGET1} Server Response"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET1} Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET1$/" }
     ]
    }
   ]
  },
  {
   "title": "$HTTP_TARGET2 - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "HTTP Get Time" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_get_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET2} Page Load" ], "type": "alias" }
      ],
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${HTTP_TARGET2} Server Response"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET2} Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET2$/" }
     ]
    }
   ]
  },
  {
   "title": "$HTTP_TARGET3 - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "HTTP Get Time" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_get_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET3} Page Load" ], "type": "alias" }
      ],
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${HTTP_TARGET3} Server Response"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET3} Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET3$/" }
     ]
    }
   ]
  },
  {
   "title": "$HTTP_TARGET4 - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms", "label": "HTTP Get Time" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_get_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET4} Page Load" ], "type": "alias" }
      ],
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${HTTP_TARGET4} Server Response"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET4} Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET4$/" }
     ]
    }
   ]
  },
  {
   "title": "$HTTP_TARGET5 - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms", "label": "HTTP Get Time" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_get_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET5} Page Load" ], "type": "alias" }
      ],
      [
       { "params": [ "http_server_response_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${HTTP_TARGET5} Server Response"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET5$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-http",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "http_status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "${HTTP_TARGET5} Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "http_target", "operator": "=~", "value": "/^$HTTP_TARGET5$/" }
     ]
    }
   ]
  },
  { "title": "Network Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Layer 2 TX Retries - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "L2 Retry Count" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "wiperf-network",
     "query": "SELECT difference(last(\"tx_retries\")) AS \"TX Retry Count\" FROM \"wiperf-network\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "tx_retries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TX Retry Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Connection Rates/Signal - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Phy Rate (Mbps)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "tx_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx PHY Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "rx_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx PHY Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "signal_level_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Signal Level (dBm)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Connection Details - $WLANPi",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "wiperf-network",
     "query": "SELECT \"bssid\" AS \"BSSID\", \"ssid\" AS \"SSID\", \"channel\" AS \"Channel\", \"channel_width\" AS \"Channel Width\", \"tx_rate_mbps\" AS \"Tx Phy Rate (Mbps)\", \"rx_rate_mbps\" AS \"Rx Phy Rate (Mbps)\", \"signal_level_dbm\" AS \"RSSI (dBm)\" FROM \"wiperf-network\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bssid" ], "type": "field" },
       { "params": [ "BSSID" ], "type": "alias" }
      ],
      [
       { "params": [ "ssid" ], "type": "field" },
       { "params": [ "SSID" ], "type": "alias" }
      ],
      [
       { "params": [ "channel" ], "type": "field" },
       { "params": [ "Channel" ], "type": "alias" }
      ],
      [
       { "params": [ "channel_width" ], "type": "field" },
       { "params": [ "Width (MHz)" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_rate_mbps" ], "type": "field" },
       { "params": [ "Tx Rate (Mbps)" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_rate_mbps" ], "type": "field" },
       { "params": [ "Rx Rate (Mbps)" ], "type": "alias" }
      ],
      [
       { "params": [ "signal_level_dbm" ], "type": "field" },
       { "params": [ "RSSI (dBm)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless MCS (if supported by NIC) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "MCS" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "tx_mcs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx MCS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "rx_mcs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx MCS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  }
 ]
}